#ifndef PSF2_PLAYER_VERSION_H
#define PSF2_PLAYER_VERSION_H

#define PSF2_PLAYER_VERSION_MAJOR 1
#define PSF2_PLAYER_VERSION_MINOR 59
#define PSF2_PLAYER_VERSION_PATCH 0
#define PSF2_PLAYER_VERSION_BUILD 0
#define PSF2_PLAYER_VERSION_STRING "1.59"
#define PSF2_PLAYER_VERSION_DISPLAY "Ver 1.59"

#endif

